[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.consumeables.cards[i]:calculate_perishable()'''
position = 'after'
payload = '''G.consumeables.cards[i]:calculate_antichrome()'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.hand.cards[i]:calculate_perishable()'''
position = 'after'
payload = '''G.hand.cards[i]:calculate_antichrome()'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.deck.cards[i]:calculate_perishable()'''
position = 'after'
payload = '''G.deck.cards[i]:calculate_antichrome()'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.discard.cards[i]:calculate_perishable()'''
position = 'after'
payload = '''G.discard.cards[i]:calculate_antichrome()'''
match_indent = true
